---
- hosts: master
  gather_facts: yes
  become: yes
  roles:
    - { role: kubernetes/master, tags: master }

- hosts: nodes
  gather_facts: no
  become: yes
  roles:
    - { role: kubernetes/node, tags: node }

- hosts: master
  gather_facts: no
  become: yes
  roles:
    - { role: cni, tags: cni }
...
